default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  adapter: mysql2
  database:  master_test_shard #marketplace_central_development
  host: localhost
  pool: 15
  username: root
  password:
  shards:
    1:
      database: test_shard
      host: 127.0.0.1
      pool: 15
      username: root
      password:
    2:
      database: test_shard1
      host: 52.221.61.181
      pool: 15
      username: root
      password:

